import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';
import { verifyResearchCapsuleBundle } from '../packages/constraint-core/src/capsuleVerify.js';

const output = path.resolve(process.argv[2] || '_review_receipt_context');
const url = process.env.CASE_WORKBENCH_URL || 'http://127.0.0.1:4173/';
const l0 = 'PROVENANCE-L0-BASE';
const l2 = 'PROVENANCE-L2-COUNTERFACTUAL';
const route = (scenario) => `#case/TYN-001?policy=LAB-CASE-OPEN-004&scenario=${scenario}&lens=constraints`;
await fs.mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(url + route(l0), { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: /^Open receipt$/ }).click();
  await page.locator('.receipt-detail').filter({ hasText: l0 }).waitFor();
  const firstHash = new URL(page.url()).hash;
  const firstId = firstHash.split('?')[0];
  await page.evaluate((hash) => { window.location.hash = hash; }, route(l2));
  await page.getByRole('button', { name: /^Open receipt$/ }).click();
  await page.locator('.receipt-detail').filter({ hasText: l2 }).waitFor();
  assert.equal(new URL(page.url()).hash.split('?')[0], firstId, 'both scenarios share this deterministic decision identity');
  await page.evaluate((hash) => { window.location.hash = hash; }, firstHash);
  await page.locator('.receipt-detail').filter({ hasText: l0 }).waitFor();
  const capsuleButton = page.getByRole('button', { name: /^Capsule bundle$/ });
  await capsuleButton.waitFor();
  await page.waitForFunction(() => ![...document.querySelectorAll('button')].find((button) => button.textContent.includes('Capsule bundle'))?.disabled);
  const downloadPromise = page.waitForEvent('download');
  await capsuleButton.click();
  const download = await downloadPromise;
  const capsuleFile = path.join(output, 'receipt-l0-capsule.json');
  await download.saveAs(capsuleFile);
  const bundle = JSON.parse(await fs.readFile(capsuleFile, 'utf8'));
  assert.equal(bundle.manifest.assurance_scenario, l0);
  assert.equal(JSON.parse(bundle.files['reproduction.json']).assurance_scenario, l0);
  assert.equal(JSON.parse(bundle.files['decision-receipt.json']).decision_id, decodeURIComponent(firstId.split('/')[1]));
  const verification = await verifyResearchCapsuleBundle(bundle);
  assert.equal(verification.summary.capsule_integrity, 'PASS');
  assert.equal(verification.summary.schema_validation, 'PASS');
  const receiptPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: /^Receipt JSON$/ }).click();
  const receiptFile = path.join(output, 'receipt-l0.json');
  await (await receiptPromise).saveAs(receiptFile);
  assert.deepEqual(JSON.parse(await fs.readFile(receiptFile, 'utf8')), JSON.parse(bundle.files['decision-receipt.json']));
  assert.deepEqual(errors, []);
  console.log('PASS: L0 → L2 → original L0 receipt route; shared decision ID; matching receipt/capsule downloads; no browser errors');
} finally { await browser.close(); }
