const fs = require("fs");
const path = require("path");
const { ethers } = require("ethers");

const ROOT = path.join(__dirname, "..");

function getArg(name, fallback = null) {
  const prefix = `--${name}=`;
  const found = process.argv.find((arg) => arg.startsWith(prefix));
  return found ? found.slice(prefix.length) : fallback;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function readJson(filePath, fallback) {
  if (!fs.existsSync(filePath)) return fallback;
  return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

function writeJson(filePath, payload) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, `${JSON.stringify(payload, null, 2)}\n`, "utf-8");
}

function isoTimestamp(value, field) {
  const millis = Date.parse(value);
  if (!Number.isFinite(millis)) {
    throw new Error(`${field} must be an ISO-like timestamp`);
  }
  return new Date(millis).toISOString().replace(".000Z", "Z");
}

function validateMeter(meter) {
  if (!meter.meter_id) throw new Error("meter_id required");
  if (!meter.site_id) throw new Error("site_id required");
  if (!ethers.isAddress(meter.device_address)) throw new Error("device_address must be an Ethereum address");

  const capacity = Number(meter.capacity_kw);
  if (!Number.isFinite(capacity) || capacity <= 0) {
    throw new Error("capacity_kw must be positive");
  }
  if (capacity > 50_000) {
    throw new Error("capacity_kw is too high for pilot onboarding");
  }

  const activeAfterMs = Date.parse(meter.active_after);
  const activeUntilMs = Date.parse(meter.active_until);
  if (!Number.isFinite(activeAfterMs) || !Number.isFinite(activeUntilMs)) {
    throw new Error("active_after and active_until must be valid timestamps");
  }
  if (activeAfterMs >= activeUntilMs) {
    throw new Error("active_after must be before active_until");
  }
}

function buildMeter(options) {
  let deviceAddress = options.deviceAddress;
  const generated = {};

  if (options.generateDevKey) {
    const wallet = ethers.Wallet.createRandom();
    deviceAddress = wallet.address;
    generated.warning = "DEV ONLY. Do not use generated private keys for production meter custody.";
    generated.private_key = wallet.privateKey;
  }

  if (!deviceAddress) {
    throw new Error("--device-address is required unless --generate-dev-key is set");
  }
  if (!ethers.isAddress(deviceAddress)) {
    throw new Error("device_address must be an Ethereum address");
  }

  const meter = {
    meter_id: String(options.meterId || "").trim(),
    site_id: String(options.siteId || "").trim(),
    device_address: ethers.getAddress(deviceAddress),
    capacity_kw: Number(options.capacityKw),
    active_after: isoTimestamp(options.activeAfter || new Date().toISOString(), "active_after"),
    active_until: isoTimestamp(options.activeUntil || "2027-01-01T00:00:00Z", "active_until"),
  };
  validateMeter(meter);
  return { meter, generated };
}

function upsertMeter(registry, meter, options = {}) {
  const next = {
    schema: registry.schema || "SPK_METER_REGISTRY_V1",
    generated_at: new Date().toISOString(),
    meters: Array.isArray(registry.meters) ? [...registry.meters] : [],
  };

  const existingIndex = next.meters.findIndex((item) => String(item.meter_id) === meter.meter_id);
  if (existingIndex >= 0 && !options.replace) {
    throw new Error(`meter ${meter.meter_id} already exists; pass --replace to update it`);
  }

  if (existingIndex >= 0) {
    next.meters[existingIndex] = meter;
  } else {
    next.meters.push(meter);
  }

  next.meters.sort((a, b) => String(a.meter_id).localeCompare(String(b.meter_id)));
  return next;
}

function toMarkdown(result) {
  const lines = [
    "# Meter Onboarding Output",
    "",
    `- generated_at: \`${result.generated_at}\``,
    `- registry_path: \`${result.registry_path}\``,
    `- meter_id: \`${result.meter.meter_id}\``,
    `- site_id: \`${result.meter.site_id}\``,
    `- device_address: \`${result.meter.device_address}\``,
    `- capacity_kw: \`${result.meter.capacity_kw}\``,
    `- active_after: \`${result.meter.active_after}\``,
    `- active_until: \`${result.meter.active_until}\``,
    `- registry_meter_count: \`${result.registry_meter_count}\``,
    "",
    "## Custody Note",
    "",
    result.generated.private_key
      ? "A development private key was generated for local testing. Do not use it for production meter custody."
      : "No private key was written. Production onboarding should register a device address generated by the meter, gateway, or hardware security module.",
    "",
  ];

  return lines.join("\n");
}

function writeText(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, value, "utf-8");
}

function main() {
  const registryPath = path.resolve(ROOT, getArg("registry", "data/attestations/meter_registry.json"));
  const outPath = path.resolve(ROOT, getArg("out", registryPath));
  const receiptPath = path.resolve(ROOT, getArg("receipt", "docs/project/METER_ONBOARDING_RECEIPT.md"));
  const registry = readJson(registryPath, {
    schema: "SPK_METER_REGISTRY_V1",
    generated_at: new Date().toISOString(),
    meters: [],
  });

  const { meter, generated } = buildMeter({
    meterId: getArg("meter-id"),
    siteId: getArg("site-id"),
    deviceAddress: getArg("device-address"),
    capacityKw: getArg("capacity-kw"),
    activeAfter: getArg("active-after", "2026-01-01T00:00:00Z"),
    activeUntil: getArg("active-until", "2027-01-01T00:00:00Z"),
    generateDevKey: hasFlag("generate-dev-key"),
  });

  const next = upsertMeter(registry, meter, { replace: hasFlag("replace") });
  const result = {
    generated_at: next.generated_at,
    registry_path: path.relative(ROOT, outPath),
    meter,
    registry_meter_count: next.meters.length,
    generated,
  };

  writeJson(outPath, next);
  writeText(receiptPath, toMarkdown(result));
  console.log(`wrote: ${outPath}`);
  console.log(`wrote: ${receiptPath}`);
  console.log(`meter: ${meter.meter_id} (${meter.device_address})`);
  if (generated.private_key) {
    console.log("generated development private key; see output custody note");
  }
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}

module.exports = {
  buildMeter,
  upsertMeter,
  validateMeter,
};
